version: "3.4"

services:
  kiddoLullaby1:
    image: kiddoLullaby
    container_name: kiddoLullaby1
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ../kiddoLullaby1:/config
    env_file: kiddoLullaby1.env